repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [ --safe, --config=./pyproject.toml ]
        exclude: "docs"

  - repo: https://github.com/LilSpazJoekp/docstrfmt
    hooks:
      - id: docstrfmt
        require_serial: true
    rev: v1.5.1

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev:  v0.0.291
    hooks:
      - id: ruff
        args: [ --config=./pyproject.toml ]
